trigger:
  branches:
    include:
      - main
 
pool:
  vmImage: 'windows-latest'
  name: mymachine
 
steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 7.x
    installationPath: $(Agent.ToolsDirectory)/dotnet